language: python

install:
    - pip install codecov

python :
    - "2.7"

env:
    global:
        - source: env.sh

script:
    - echo $PYTHONPATH; python unittest/runall.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
