language: python

install:
    - pip install codecov

python :
    - "2.7"

env:
    global:
        - source env.sh

script:
    - ls -al
    - sh env.sh >> ~/.bash_profile
    - echo $PYTHONPATH
    - sh env.sh >> ~/.profile
    - echo $PYTHONPATH
    - ls -al
    - cat ~/.bash_profile
    - echo $PYTHONPATH
    - source ~/.bash_profile
    - echo $PYTHONPATH
    - pwd
    - source ~/.profile
    - echo $PYTHONPATH
    - pwd; echo $PYTHONAPTH
    - echo which python
    - echo $PYTHONPATH; python unittest/runall.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
