language: python

install:
    - pip install codecov

python :
    - "2.7"

befor_script:
    - source ./env.sh

script:
    - source env.sh
    - source env.sh; coverage run unittest/runall.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
