language: python

install:
    - pip install codecov

python :
    - "2.7"

matrix:
    include:
        - env: >
            PYTHONPATH:`pwd`/src

script:
    - python unittest/runall.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
