language: python

install:
    - pip install codecov

python :
    - "2.7"

env:
    global:
        - source env.sh

befor_script:
    - ls -al
    - sh env.sh >> ~/.bash_profile
    - ls -al

script:
    - cat ~/.bash_profile
    - coverage run unittest/runall.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
