language: python

install:
    - pip install codecov

python :
    - "2.7"

env:
    global:
        - source env.sh

befor_script:
    - echo 'Test=============='
    - sh env.sh >> ~/.profile
    - cat ~/.profile

script:
    - cat ~/.profile
    - coverage run unittest/runall.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
